apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base
  
resources:
    - resources/pvc.yaml
    - resources/pv.yaml
    - resources/storageclass.yaml

commonLabels:
  env: prod

namespace: prometheus