apiVersion: apps/v1
kind: Deployment
metadata:
  name:  grafana
  labels:
    app:  grafana
spec:
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  grafana
    spec:
      containers:
      - name:  grafana
        image:  grafana/grafana:7.5.17
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 200m
            memory: 500M
          limits:
            cpu: 100m
            memory: 250M
        ports:
        - containerPort:  3000
          name:  grafana